### ISSUE TITLE
Review feedback from GDC 2024

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-organ-gallery-in-vr#427]
- [ ] Upload videos to Google Drive
 - [ ] Summarize feedback in Google Doc

**Comment by andreasbueckle** [comment]
@thespiritninja 
Have you had a chance to upload the recordings to Google Drive?

**Comment by thespiritninja** [comment]
I have uploaded the recordings, the zip files have all the recordings in them

**Comment by andreasbueckle** [comment]
Got it, thanks!
